Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: helloworld.App::invoke
      CodeUri: /Users/zeeroiq/projects/aws-learning/first-lambda/HelloWorldFunction
      Runtime: java17
      Architectures:
        - x86_64